# Generated by Django 4.1.3 on 2022-11-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=30)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("desc", models.TextField()),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
            options={"ordering": ["-date_created", "-name"],},
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ingredients", models.TextField()),
                ("method", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="")),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
            options={"ordering": ["-date_created", "name"],},
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.CharField(max_length=100)),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
            options={"ordering": ["-date_created", "review"],},
        ),
    ]
